nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /

www:
  image: nginx:1.21-alpine
  restart: always
  expose: 
    - "80"
  volumes: 
    - /data/www/:/usr/share/nginx/html/
  environment: 
    - VIRTUAL_HOST=pablodelacuesta.es, www.pablodelacuesta.es