version: "3"

volumes: 
  certs:
  vhost:
  html:
  acme:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"


  www:
    build: .
    restart: always
    expose: 
      - "80"
    environment: 
      - VIRTUAL_HOST=pablodelacuesta.es, www.pablodelacuesta.es
      - LETSENCRYPT_HOST=pablodelacuesta.es

  api:
    image: nginx:1.21-alpine
    restart: always
    expose: 
      - "80"
    environment: 
      - VIRTUAL_HOST=api.pablodelacuesta.es

  letsencrypt:
    image: nginxproxy/acme-companion
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment: 
      - DEFAULT_EMAIL=pablodelacuesta@outlook.es
