name: Send my html to digital ocean droplet
on: push
jobs:
  build:
    name: Hello world action
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: whoami
    - run: ls
    - run: docker-compose restart
    # - name: Run docker-compose to restart
    #   uses: sudo-bot/action-docker-compose@latest
    #   with:
    #     cli-args: "restart"